name: 'Build'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - gh-actions

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amazon/aws-glue-libs:glue_libs_3.0.0_image_01
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pip3 install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: bin/test
      - name: Build wheel
        run: poetry build -f wheel
      - uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'dist'
          DEST_DIR: 'dist'
